"use strict";

// Imported exercise name -> the muscles that receive training stimulus.
// The importer will trim exercise names before looking them up, so a small
// spelling difference will not be confused with leading/trailing spaces.
// These are sensible defaults, not medical facts: edit them to match how you train.
//
// Volume in this project means hard-set count, not weight x reps (tonnage).
// Each logged working set counts as one set for every listed primary muscle.
// Secondary muscles will be shown separately as contributing/indirect sets.
const exerciseMuscles = {
  "Back Extension": { primary: ["lower back"], secondary: ["glutes", "hamstrings"] },
  "Bench Press (Barbell)": { primary: ["chest"], secondary: ["triceps", "front delts"] },
  "Bench Press (Dumbbell)": { primary: ["chest"], secondary: ["triceps", "front delts"] },
  "Bent Over Row (Barbell)": { primary: ["back"], secondary: ["biceps", "rear delts"] },
  "Bicep Curl (Cable)": { primary: ["biceps"], secondary: [] },
  "Bicep Curl (Dumbbell)": { primary: ["biceps"], secondary: [] },
  "Bulgarian Split Squat": { primary: ["quads", "glutes"], secondary: ["hamstrings"] },
  "Calf Press on Seated Leg Press": { primary: ["calves"], secondary: [] },
  "Chest Fly": { primary: ["chest"], secondary: [] },
  "Chest Press (Machine)": { primary: ["chest"], secondary: ["triceps", "front delts"] },
  "Chest Press (plate loaded)": { primary: ["chest"], secondary: ["triceps", "front delts"] },
  "Deadlift (Barbell)": { primary: ["glutes", "hamstrings", "lower back"], secondary: ["back", "quads"] },
  "Diverging Seated Row": { primary: ["back"], secondary: ["biceps", "rear delts"] },
  "Hack Squat": { primary: ["quads"], secondary: ["glutes"] },
  "Hammer Curl (Cable)": { primary: ["biceps"], secondary: ["forearms"] },
  "Hip Adductor (Machine)": { primary: ["adductors"], secondary: [] },
  "Hip Thrust (Barbell)": { primary: ["glutes"], secondary: ["hamstrings"] },
  "Hip Thrust (Machine)": { primary: ["glutes"], secondary: ["hamstrings"] },
  "Incline Bench Press (Barbell)": { primary: ["chest"], secondary: ["triceps", "front delts"] },
  "Incline Bench Press (Dumbbell)": { primary: ["chest"], secondary: ["triceps", "front delts"] },
  "Incline Bench Press (Smith Machine)": { primary: ["chest"], secondary: ["triceps", "front delts"] },
  "Iso-Lateral Chest Press (Machine)": { primary: ["chest"], secondary: ["triceps", "front delts"] },
  "Knee Raise (Captain's Chair)": { primary: ["abs"], secondary: ["hip flexors"] },
  "Lat Pulldown (Cable)": { primary: ["back"], secondary: ["biceps"] },
  "Lat Pulldown (Machine)": { primary: ["back"], secondary: ["biceps"] },
  "Lat Pulldown (Single Arm)": { primary: ["back"], secondary: ["biceps"] },
  "Lateral Raise (Cable)": { primary: ["side delts"], secondary: [] },
  "Lateral Raise (Dumbbell)": { primary: ["side delts"], secondary: [] },
  "Leg Extension (Machine)": { primary: ["quads"], secondary: [] },
  "Leg Press": { primary: ["quads"], secondary: ["glutes", "hamstrings"] },
  "Lunge (Barbell)": { primary: ["quads", "glutes"], secondary: ["hamstrings"] },
  "Lying Leg Curl (Machine)": { primary: ["hamstrings"], secondary: [] },
  "Overhead Press (Barbell)": { primary: ["front delts"], secondary: ["triceps", "side delts"] },
  "Overhead Press (Dumbbell)": { primary: ["front delts"], secondary: ["triceps", "side delts"] },
  "Paused Squat": { primary: ["quads", "glutes"], secondary: ["hamstrings", "lower back"] },
  "Pec Deck (Machine)": { primary: ["chest"], secondary: [] },
  "Preacher Curl (Barbell)": { primary: ["biceps"], secondary: [] },
  "Pull Up": { primary: ["back"], secondary: ["biceps"] },
  "Reverse Fly (Cable)": { primary: ["rear delts"], secondary: ["back"] },
  "Reverse Fly (Machine)": { primary: ["rear delts"], secondary: ["back"] },
  "Romanian Deadlift (Barbell)": { primary: ["hamstrings", "glutes"], secondary: ["lower back"] },
  "Seated Calf Raise (Plate Loaded)": { primary: ["calves"], secondary: [] },
  "Seated Dip": { primary: ["triceps"], secondary: ["chest", "front delts"] },
  "Seated Leg Curl (Machine)": { primary: ["hamstrings"], secondary: [] },
  "Seated Row (Cable)": { primary: ["back"], secondary: ["biceps", "rear delts"] },
  "Seated Row (High Grip)": { primary: ["back"], secondary: ["biceps", "rear delts"] },
  "Seated Row (Machine)": { primary: ["back"], secondary: ["biceps", "rear delts"] },
  "Seated Row (Plate Loaded)": { primary: ["back"], secondary: ["biceps", "rear delts"] },
  "Single Leg Leg Press": { primary: ["quads"], secondary: ["glutes", "hamstrings"] },
  "Squat (Barbell)": { primary: ["quads", "glutes"], secondary: ["hamstrings", "lower back"] },
  "Standing Calf Raise (Machine)": { primary: ["calves"], secondary: [] },
  "Triceps Extension": { primary: ["triceps"], secondary: [] },
  "Triceps Extension (Cable)": { primary: ["triceps"], secondary: [] },
  "Triceps Pushdown (Cable - Straight Bar)": { primary: ["triceps"], secondary: [] },
  "Wrist Curl (Cable)": { primary: ["forearms"], secondary: [] },
};
