"use strict";

// Imported exercise name -> the muscles that receive training stimulus.
// The importer will trim exercise names before looking them up, so a small
// spelling difference will not be confused with leading/trailing spaces.
// These are sensible defaults, not medical facts: edit them to match how you train.
//
// Volume in this project means hard-set count, not weight x reps (tonnage).
// Each logged working set counts as one set for every listed primary muscle.
// Secondary muscles will be shown separately as contributing/indirect sets.
const exerciseMuscles = {
  "Back Extension": { primary: ["lower back"], secondary: ["glutes", "hamstrings"] },
  "Bench Press (Barbell)": { primary: ["chest"], secondary: ["triceps", "front delts"] },
  "Bench Press (Dumbbell)": { primary: ["chest"], secondary: ["triceps", "front delts"] },
  "Bent Over Row (Barbell)": { primary: ["back"], secondary: ["biceps", "rear delts"] },
  "Bicep Curl (Cable)": { primary: ["biceps"], secondary: [] },
  "Bicep Curl (Dumbbell)": { primary: ["biceps"], secondary: [] },
  "Bulgarian Split Squat": { primary: ["quads", "glutes"], secondary: ["hamstrings"] },
  "Calf Press on Seated Leg Press": { primary: ["calves"], secondary: [] },
  "Chest Fly": { primary: ["chest"], secondary: [] },
  "Chest Press (Machine)": { primary: ["chest"], secondary: ["triceps", "front delts"] },
  "Chest Press (plate loaded)": { primary: ["chest"], secondary: ["triceps", "front delts"] },
  "Deadlift (Barbell)": { primary: ["glutes", "hamstrings", "lower back"], secondary: ["back", "quads"] },
  "Diverging Seated Row": { primary: ["back"], secondary: ["biceps", "rear delts"] },
  "Hack Squat": { primary: ["quads"], secondary: ["glutes"] },
  "Hammer Curl (Cable)": { primary: ["biceps"], secondary: ["forearms"] },
  "Hip Adductor (Machine)": { primary: ["adductors"], secondary: [] },
  "Hip Thrust (Barbell)": { primary: ["glutes"], secondary: ["hamstrings"] },
  "Hip Thrust (Machine)": { primary: ["glutes"], secondary: ["hamstrings"] },
  "Incline Bench Press (Barbell)": { primary: ["chest"], secondary: ["triceps", "front delts"] },
  "Incline Bench Press (Dumbbell)": { primary: ["chest"], secondary: ["triceps", "front delts"] },
  "Incline Bench Press (Smith Machine)": { primary: ["chest"], secondary: ["triceps", "front delts"] },
  "Iso-Lateral Chest Press (Machine)": { primary: ["chest"], secondary: ["triceps", "front delts"] },
  "Knee Raise (Captain's Chair)": { primary: ["abs"], secondary: ["hip flexors"] },
  "Lat Pulldown (Cable)": { primary: ["back"], secondary: ["biceps"] },
  "Lat Pulldown (Machine)": { primary: ["back"], secondary: ["biceps"] },
  "Lat Pulldown (Single Arm)": { primary: ["back"], secondary: ["biceps"] },
  "Lateral Raise (Cable)": { primary: ["side delts"], secondary: [] },
  "Lateral Raise (Dumbbell)": { primary: ["side delts"], secondary: [] },
  "Leg Extension (Machine)": { primary: ["quads"], secondary: [] },
  "Leg Press": { primary: ["quads"], secondary: ["glutes", "hamstrings"] },
  "Lunge (Barbell)": { primary: ["quads", "glutes"], secondary: ["hamstrings"] },
  "Lying Leg Curl (Machine)": { primary: ["hamstrings"], secondary: [] },
  "Overhead Press (Barbell)": { primary: ["front delts"], secondary: ["triceps", "side delts"] },
  "Overhead Press (Dumbbell)": { primary: ["front delts"], secondary: ["triceps", "side delts"] },
  "Paused Squat": { primary: ["quads", "glutes"], secondary: ["hamstrings", "lower back"] },
  "Pec Deck (Machine)": { primary: ["chest"], secondary: [] },
  "Preacher Curl (Barbell)": { primary: ["biceps"], secondary: [] },
  "Pull Up": { primary: ["back"], secondary: ["biceps"] },
  "Reverse Fly (Cable)": { primary: ["rear delts"], secondary: ["back"] },
  "Reverse Fly (Machine)": { primary: ["rear delts"], secondary: ["back"] },
  "Romanian Deadlift (Barbell)": { primary: ["hamstrings", "glutes"], secondary: ["lower back"] },
  "Seated Calf Raise (Plate Loaded)": { primary: ["calves"], secondary: [] },
  "Seated Dip": { primary: ["triceps"], secondary: ["chest", "front delts"] },
  "Seated Leg Curl (Machine)": { primary: ["hamstrings"], secondary: [] },
  "Seated Row (Cable)": { primary: ["back"], secondary: ["biceps", "rear delts"] },
  "Seated Row (High Grip)": { primary: ["back"], secondary: ["biceps", "rear delts"] },
  "Seated Row (Machine)": { primary: ["back"], secondary: ["biceps", "rear delts"] },
  "Seated Row (Plate Loaded)": { primary: ["back"], secondary: ["biceps", "rear delts"] },
  "Single Leg Leg Press": { primary: ["quads"], secondary: ["glutes", "hamstrings"] },
  "Squat (Barbell)": { primary: ["quads", "glutes"], secondary: ["hamstrings", "lower back"] },
  "Standing Calf Raise (Machine)": { primary: ["calves"], secondary: [] },
  "Triceps Extension": { primary: ["triceps"], secondary: [] },
  "Triceps Extension (Cable)": { primary: ["triceps"], secondary: [] },
  "Triceps Pushdown (Cable - Straight Bar)": { primary: ["triceps"], secondary: [] },
  "Wrist Curl (Cable)": { primary: ["forearms"], secondary: [] },

  // Additional Strong labels and gym-specific variants.
  "Adductor Machine Ambachtsveld": { primary: ["adductors"], secondary: [] },
  "Back Extension (Machine)": { primary: ["lower back"], secondary: ["glutes", "hamstrings"] },
  "Bench Press - Close Grip (Barbell)": { primary: ["triceps"], secondary: ["chest", "front delts"] },
  "Bench Press Machine": { primary: ["chest"], secondary: ["triceps", "front delts"] },
  "Bent Over One Arm Row (Dumbbell)": { primary: ["back"], secondary: ["biceps", "rear delts"] },
  "Bent Over Row - Underhand (Barbell)": { primary: ["back"], secondary: ["biceps", "rear delts"] },
  "Bent Over Row (Dumbbell)": { primary: ["back"], secondary: ["biceps", "rear delts"] },
  "Bicep Curl (Barbell)": { primary: ["biceps"], secondary: [] },
  "Bicep Curl (Machine)": { primary: ["biceps"], secondary: [] },
  "Bicep Curl Ambachtsveld": { primary: ["biceps"], secondary: [] },
  "Bulgarian split squat (smith)": { primary: ["quads", "glutes"], secondary: ["hamstrings"] },
  "Cable Step Up Ambachtsveld": { primary: ["quads", "glutes"], secondary: ["hamstrings"] },
  "Calf Press on Leg Press": { primary: ["calves"], secondary: [] },
  "Chest Dip": { primary: ["chest"], secondary: ["triceps", "front delts"] },
  "Chest Fly (Band)": { primary: ["chest"], secondary: [] },
  "Chest fly (cable)": { primary: ["chest"], secondary: [] },
  "Chin Up": { primary: ["back"], secondary: ["biceps"] },
  "Defecit BSS Ambachtsveld": { primary: ["quads", "glutes"], secondary: ["hamstrings"] },
  "Deficit bulgarian split squat": { primary: ["quads", "glutes"], secondary: ["hamstrings"] },
  "Deficit Deadlift (Barbell)": { primary: ["glutes", "hamstrings", "lower back"], secondary: ["back", "quads"] },
  "Deficit reverse lunge": { primary: ["quads", "glutes"], secondary: ["hamstrings"] },
  "Dumbell step up": { primary: ["quads", "glutes"], secondary: ["hamstrings"] },
  "Face Pull (Cable)": { primary: ["rear delts"], secondary: ["back"] },
  "Face Pulls Ambachtsveld": { primary: ["rear delts"], secondary: ["back"] },
  "Floor Press (Barbell)": { primary: ["chest"], secondary: ["triceps", "front delts"] },
  "Front Raise (Dumbbell)": { primary: ["front delts"], secondary: [] },
  "Glute Kickback (Machine)": { primary: ["glutes"], secondary: ["hamstrings"] },
  "Glute Kickback Ambachtsveld": { primary: ["glutes"], secondary: ["hamstrings"] },
  "Goodmorning Smith Machine": { primary: ["hamstrings", "glutes"], secondary: ["lower back"] },
  "Hammer Curl (Dumbbell)": { primary: ["biceps"], secondary: ["forearms"] },
  "Heel elevated db squat": { primary: ["quads"], secondary: ["glutes"] },
  "High bar pausen squat": { primary: ["quads", "glutes"], secondary: ["hamstrings", "lower back"] },
  "Hip Abductor (Machine)": { primary: ["glutes"], secondary: [] },
  "Hip thrust": { primary: ["glutes"], secondary: ["hamstrings"] },
  "Hip Thrust (Bodyweight)": { primary: ["glutes"], secondary: ["hamstrings"] },
  "Hipthrust Smith Machine": { primary: ["glutes"], secondary: ["hamstrings"] },
  "Incline Chest Fly (Dumbbell)": { primary: ["chest"], secondary: [] },
  "Incline Chest Press (Machine)": { primary: ["chest"], secondary: ["triceps", "front delts"] },
  "Incline Row (Dumbbell)": { primary: ["back"], secondary: ["biceps", "rear delts"] },
  "Lateral raise (zittend)": { primary: ["side delts"], secondary: [] },
  "Lateral Raise Ambachtsveld": { primary: ["side delts"], secondary: [] },
  "Leg Extensions Ambachtsveld": { primary: ["quads"], secondary: [] },
  "Leg press schuine single leg": { primary: ["quads"], secondary: ["glutes", "hamstrings"] },
  "Low Bar Pause Squat": { primary: ["quads", "glutes"], secondary: ["hamstrings", "lower back"] },
  "Lunge (Dumbbell)": { primary: ["quads", "glutes"], secondary: ["hamstrings"] },
  "Lying Leg Curl Ambachtsveld": { primary: ["hamstrings"], secondary: [] },
  "Neutral shoulder press": { primary: ["front delts"], secondary: ["triceps", "side delts"] },
  "Overhead Press (Cable)": { primary: ["front delts"], secondary: ["triceps", "side delts"] },
  "Pause squats": { primary: ["quads", "glutes"], secondary: ["hamstrings", "lower back"] },
  "Pendlay Row (Barbell)": { primary: ["back"], secondary: ["biceps", "rear delts"] },
  "Preacher Curl (Dumbbell)": { primary: ["biceps"], secondary: [] },
  "Pull Up (Band)": { primary: ["back"], secondary: ["biceps"] },
  "Pull ups 1 1/4": { primary: ["back"], secondary: ["biceps"] },
  "Pullover (Machine)": { primary: ["back"], secondary: ["chest", "triceps"] },
  "Push Up": { primary: ["chest"], secondary: ["triceps", "front delts"] },
  "Rear foot elevated split squat": { primary: ["quads", "glutes"], secondary: ["hamstrings"] },
  "Reverse Fly (Dumbbell)": { primary: ["rear delts"], secondary: ["back"] },
  "Reverse Fly Ambachtsveld": { primary: ["rear delts"], secondary: ["back"] },
  "Reverse Fly Cable Ambachtsveld": { primary: ["rear delts"], secondary: ["back"] },
  "Romanian Deadlift (Dumbbell)": { primary: ["hamstrings", "glutes"], secondary: ["lower back"] },
  "Seated Abductions Ambachtsveld": { primary: ["glutes"], secondary: [] },
  "Seated Calf Raise (Machine)": { primary: ["calves"], secondary: [] },
  "Seated high row de maten": { primary: ["back"], secondary: ["biceps", "rear delts"] },
  "Seated Leg Curl Ambachtsveld": { primary: ["hamstrings"], secondary: [] },
  "Seated Leg Press (Machine)": { primary: ["quads"], secondary: ["glutes", "hamstrings"] },
  "Seated Overhead Press (Dumbbell)": { primary: ["front delts"], secondary: ["triceps", "side delts"] },
  "Seated row de maten": { primary: ["back"], secondary: ["biceps", "rear delts"] },
  "Seated Row Ambachtsveld": { primary: ["back"], secondary: ["biceps", "rear delts"] },
  "Seated Row Matrix": { primary: ["back"], secondary: ["biceps", "rear delts"] },
  "Seated row single arm": { primary: ["back"], secondary: ["biceps", "rear delts"] },
  "Seated Wide-Grip Row (Cable)": { primary: ["back"], secondary: ["biceps", "rear delts"] },
  "Shoulder Press (Machine)": { primary: ["front delts"], secondary: ["triceps", "side delts"] },
  "Shoulder Press (Plate Loaded)": { primary: ["front delts"], secondary: ["triceps", "side delts"] },
  "Single arm bicep curl": { primary: ["biceps"], secondary: [] },
  "Single arm row": { primary: ["back"], secondary: ["biceps", "rear delts"] },
  "Single arm tricep push down": { primary: ["triceps"], secondary: [] },
  "Single leg press": { primary: ["quads"], secondary: ["glutes", "hamstrings"] },
  "Sissy squat": { primary: ["quads"], secondary: [] },
  "Skullcrusher (Barbell)": { primary: ["triceps"], secondary: [] },
  "Skullcrusher (Dumbbell)": { primary: ["triceps"], secondary: [] },
  "Smith Machine Elevated Reverse Lunge": { primary: ["quads", "glutes"], secondary: ["hamstrings"] },
  "Squat (Bodyweight)": { primary: ["quads", "glutes"], secondary: ["hamstrings", "lower back"] },
  "Squat (Smith Machine)": { primary: ["quads", "glutes"], secondary: ["hamstrings", "lower back"] },
  "Standing Calf Raise (Bodyweight)": { primary: ["calves"], secondary: [] },
  "Step up cable": { primary: ["quads", "glutes"], secondary: ["hamstrings"] },
  "Step up smith": { primary: ["quads", "glutes"], secondary: ["hamstrings"] },
  "Step-up": { primary: ["quads", "glutes"], secondary: ["hamstrings"] },
  "Sumo block deadlifts": { primary: ["glutes", "hamstrings", "adductors"], secondary: ["lower back", "back", "quads"] },
  "Sumo Deadlift (Barbell)": { primary: ["glutes", "hamstrings", "adductors"], secondary: ["lower back", "back", "quads"] },
  "Sumo dumbell squat": { primary: ["quads", "glutes", "adductors"], secondary: ["hamstrings"] },
  "Tricep Pushdown Single Arm Ambachtsveld": { primary: ["triceps"], secondary: [] },
  "Triceps Dip": { primary: ["triceps"], secondary: ["chest", "front delts"] },
  "Triceps Extension (Dumbbell)": { primary: ["triceps"], secondary: [] },
  "Triceps Extension (Machine)": { primary: ["triceps"], secondary: [] },
  "Upright Row (Barbell)": { primary: ["side delts"], secondary: ["back", "biceps"] },
  "Y raise": { primary: ["rear delts"], secondary: ["back"] },
  "Y raise cable": { primary: ["rear delts"], secondary: ["back"] },
  "Zercher Squat (Barbell)": { primary: ["quads", "glutes"], secondary: ["hamstrings", "lower back"] },
};
